"""
Incident identifier parser.

Extracts a sys_id or incident number from:
  - A plain incident number:           INC0000001
  - A classic ServiceNow URL:          https://…/incident.do?sys_id=<uuid>
  - A nav_to.do URL (new format):      https://…/nav_to.do?uri=incident.do%3Fsys_id%3D<hex32>
  - A direct UUID string:              047240d5-08d4-5341-8664-8e0685c52f34
  - A 32-char hex string (no dashes):  047240d508d4534186648e0685c52f34
"""

import re
from typing import Dict
from urllib.parse import parse_qs, unquote, urlparse


# INC followed by exactly 7 digits — standard ServiceNow incident number format.
INCIDENT_NUMBER_PATTERN = re.compile(r"\bINC\d{7}\b", re.IGNORECASE)

# Standard UUID (with dashes): xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
UUID_PATTERN = re.compile(
    r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$",
    re.IGNORECASE,
)

# 32-char hex without dashes (ServiceNow sys_id in URL parameters).
HEX32_PATTERN = re.compile(r"^[0-9a-f]{32}$", re.IGNORECASE)


def _normalise_sys_id(raw: str) -> str:
    """
    Return a canonical sys_id string.

    ServiceNow URLs embed sys_ids as 32-char hex without dashes.
    Our mock data stores them as standard UUIDs (with dashes).
    We keep the dashes so the fetch service can match against incident.sys_id
    directly; the fetch service also accepts the dashless form.
    """
    stripped = raw.strip()

    # Already a proper UUID — return as-is.
    if UUID_PATTERN.match(stripped):
        return stripped

    # 32-char hex without dashes — insert dashes to form a UUID.
    if HEX32_PATTERN.match(stripped):
        h = stripped.lower()
        return f"{h[0:8]}-{h[8:12]}-{h[12:16]}-{h[16:20]}-{h[20:32]}"

    raise ValueError(f"Unrecognised sys_id format: {stripped!r}")


def _extract_sys_id_from_query(query_string: str) -> str | None:
    """Pull sys_id from a URL query string, or return None if not present."""
    params = parse_qs(query_string)
    values = params.get("sys_id", [])
    return values[0].strip() if values else None


def extract_incident_identifier(input_text: str) -> Dict[str, str]:
    """
    Extract a sys_id or incident number from user input.

    Returns a dict with keys:
        type  – "sys_id" or "number"
        value – the extracted identifier
    """
    if not input_text or not input_text.strip():
        raise ValueError("Incident input cannot be empty.")

    value = input_text.strip()
    parsed_url = urlparse(value)

    # ── URL input ─────────────────────────────────────────────────────────────
    if parsed_url.scheme and parsed_url.netloc:

        # Format 1: classic direct URL
        #   https://example.service-now.com/incident.do?sys_id=<hex32>
        raw_sys_id = _extract_sys_id_from_query(parsed_url.query)

        if raw_sys_id:
            try:
                return {"type": "sys_id", "value": _normalise_sys_id(raw_sys_id)}
            except ValueError as exc:
                raise ValueError(f"Malformed sys_id in incident link: {exc}") from exc

        # Format 2: nav_to.do URL (generated by our mock data and real ServiceNow UI)
        #   https://example.service-now.com/nav_to.do?uri=incident.do%3Fsys_id%3D<hex32>
        top_params = parse_qs(parsed_url.query)
        uri_values = top_params.get("uri", [])
        if uri_values:
            inner_uri = unquote(uri_values[0])  # e.g. "incident.do?sys_id=047240d5…"
            if "?" in inner_uri:
                inner_query = inner_uri.split("?", 1)[1]
                raw_sys_id = _extract_sys_id_from_query(inner_query)
                if raw_sys_id:
                    try:
                        return {"type": "sys_id", "value": _normalise_sys_id(raw_sys_id)}
                    except ValueError as exc:
                        raise ValueError(
                            f"Malformed sys_id in nav_to.do link: {exc}"
                        ) from exc

        # Fall back to incident number in the URL path or query
        incident_match = INCIDENT_NUMBER_PATTERN.search(value)
        if incident_match:
            return {"type": "number", "value": incident_match.group(0).upper()}

        raise ValueError(
            "Incident link does not contain a recognisable sys_id or incident number. "
            "Expected formats: …?sys_id=<uuid> or …?uri=incident.do%3Fsys_id%3D<hex32>"
        )

    # ── Plain text / bare identifier input ───────────────────────────────────

    # Exact incident number: INC0000001
    incident_match = INCIDENT_NUMBER_PATTERN.fullmatch(value)
    if incident_match:
        return {"type": "number", "value": incident_match.group(0).upper()}

    # UUID with dashes
    if UUID_PATTERN.match(value):
        return {"type": "sys_id", "value": value}

    # 32-char hex without dashes
    if HEX32_PATTERN.match(value):
        try:
            return {"type": "sys_id", "value": _normalise_sys_id(value)}
        except ValueError as exc:
            raise ValueError(str(exc)) from exc

    raise ValueError(
        "Input must be a ServiceNow incident link, incident number (INCxxxxxxx), "
        "or sys_id (UUID or 32-char hex)."
    )